### PR TITLE
V1 fixes

### LINKED ISSUE #54: Production build
Unminified bundle is 2.7mb

### LINKED ISSUE #55: Limit selector length

### LINKED ISSUE #56: Pearl thread default click handler
pasted_image_at_2017_11_27_01_02_am

### LINKED ISSUE #57: Scoreboard text overflow
allow only single line per item in scoreboard

### LINKED ISSUE #58: Scoreboard scroll

### LINKED ISSUE #59: Countdown component unmount
pasted_image_at_2017_11_27_01_01_am

### PR DESCRIPTION
**Pull request by R1ZZU**
Closes #54 
Closes #55 
Closes #56 
Closes #57 
Closes #58 
Closes #59

### CODE REVIEW

File: src/game-master/middlewares/phoenix-gm-middleware.js [hunk 1]
```diff
@@ -54,6 +54,10 @@ function send(store, payload) {
 function handleServerMessage(store, message) {
     let action;
 
+    if (MESSAGE_NAME.gameMasterSessionState && message.puzzleIndex === null) {
```
Comment (kirilknysh) [inline src/game-master/middlewares/phoenix-gm-middleware.js]: I do remember a lot of concerns about it. And finally in _qd-ui it was transformed to
```
currentRoundIndex: typeof puzzleIndex === 'number' ? puzzleIndex : -1,
```

File: src/shared/containers/AppContainer.js [hunk 2]
```diff
@@ -1,13 +1,20 @@
...
+const PureAppContainer = ({ children, ready }) => (
     <Layout>
         <Header />
-        { children }
+        { ready ? children : null }
     </Layout>
 );
 
+const AppContainer = connect(createStructuredSelector({
+    ready: state => state.username !== '',
```
Comment (kirilknysh) [inline src/shared/containers/AppContainer.js]: Potentially `''` is a valid user name. FES sends either what it got from auth, or `undefined`
